# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on: ["push", "pull_request"]

jobs:
  build:
    name: Test ICUPipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Lint with ruff
      run: poetry run ruff check ./icu_pipeline
    - name: Lint with mypy
      run: poetry run mypy ./icu_pipeline
    - name: Test with pytest and coverage
      run: poetry run pytest -v -rA --junitxml=junit/test-results.xml --cov-branch --cov-report xml --cov --random-order tests
    - name: Coveralls
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    # - name: Run mypy
    #   run: |
    #     mypy ./icu_pipeline/
